import selenium
from PIL import Image
import  time as t
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
a=webdriver.Chrome()
a.maximize_window()
a.get('https://testautomationpractice.blogspot.com/')
t.sleep(10)
a.find_element(By.XPATH,'//*[@id="name"]').send_keys('Divi')
a.find_element(By.XPATH,'//*[@id="email"]').send_keys('divi@gmail.com')
a.find_element(By.XPATH,'//*[@id="phone"]').send_keys('1234546454')
a.find_element(By.XPATH,'//*[@id="textarea"]').send_keys('Salem')
a.find_element(By.XPATH,'//*[@id="textarea"]').clear()
t.sleep(2)
a.find_element(By.XPATH,'//*[@id="textarea"]').send_keys('Namakkal')
t.sleep(2)
a.find_element(By.XPATH,'//*[@id="male"]').click()
a.find_element(By.XPATH,'//*[@id="monday"]').click()
a.find_element(By.XPATH,'//*[@id="country"]').send_keys('India')
a.find_element(By.XPATH,'//*[@id="colors"]/option[4]').click()
a.find_element(By.XPATH,'//*[@id="animals"]/option[2]').click()
t.sleep(5)
a.find_element(By.XPATH,'//*[@id="datepicker"]').send_keys("05/20/2026")
a.find_element(By.XPATH,'//*[@id="txtDate"]').click()
a.find_element(By.XPATH,'/html/body/div[5]/div/div/select[1]').click()
a.find_element(By.XPATH,'/html/body/div[5]/div/div/select[1]').send_keys("Apr")
a.find_element(By.XPATH,'/html/body/div[5]/div/div/select[2]').click()
a.find_element(By.XPATH,'/html/body/div[5]/div/div/select[2]').send_keys('2020')
a.find_element(By.XPATH,'/html/body/div[5]/table/tbody/tr[4]/td[2]/a').click()
t.sleep(10)
a.find_element(By.XPATH,'//*[@id="start-date"]').send_keys("20/05/2026")
a.find_element(By.XPATH,'//*[@id="end-date"]').send_keys("20/05/2027")
a.find_element(By.XPATH,'//*[@id="post-body-1307673142697428135"]/div[8]/button').click()
t.sleep(5)
x=a.save_screenshot("C:\\Users\\divik\\OneDrive\\screenshot.png")
y=Image.open("C:\\Users\\divik\\OneDrive\\screenshot.png")
y.show()
t.sleep(5)
a.get("https://www.amazon.in/")
t.sleep(5)
a.find_element(By.XPATH,'//*[@id="twotabsearchtextbox"]').send_keys("Mobile phone"+Keys.ENTER)
a.back()
t.sleep(5)
a.forward()
t.sleep(5)
a.refresh()
b=a.find_elements(By.XPATH,'//*[@id="search"]')
print(b.text)
print(b.get_attribute('href'))
print(b.get_attribute('class'))
print(b.value_of_css_property('height'))
print(b.is_displayed())
print(b.is_enabled())
print(b.location)

a.get("https://www.bing.com")
a.find_element(By.XPATH,'//*[@id="sb_form_q"]').send_keys("F1"+Keys.ENTER)
t.sleep(10)
a.find_element(By.XPATH,'//*[@id="r1-0"]/div[3]/h2/a/span').click()
t.sleep(5)
a.find_element(By.XPATH,'/html/body/div[2]/header/div[2]/div[2]/div/div/div[2]/a[6]/svg/g/path[3]').click()
a.find_element(By.XPATH,'//*[@id="maincontent"]/div/div/div[1]/div[2]/div/div/div[3]/div/div/div/nav/a[2]/span').click()
a.find_element(By.XPATH,'//*[@id="results-table"]/div/table/tbody/tr[1]/td[2]/a/span[2]/span[2]').click()
t.sleep(10)




